pub mod ads;
pub mod api;
pub mod apple_auth;
pub mod audio;
pub mod audio_policy;
pub mod domain;
pub mod fpl_bridge;
pub mod github_auth;
pub mod ingest;
pub mod launch_safety; // Durable launch intake; completion gates remain explicit.
pub mod mcp;
pub mod mcp_bridges;
pub mod media;
pub mod metrics;
pub mod onboarding;
pub mod openapi;
pub mod pg_accounts;
pub mod pg_ingest;
pub mod privacy;
pub mod product;
pub mod push;
pub mod ranking;
pub mod search;
pub mod share_preview;
pub mod social;
pub mod source_dispatch;
pub mod store;
pub mod subscriptions;
pub mod usage_metrics;
pub mod verification;
pub mod web_billing;

pub use api::{AppState, router};
